apiVersion: v1
kind: Service
metadata:
  name: daga-svc
  namespace: daga
spec:
  selector:
    app: daga
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: daga-svc
    protocol: TCP
    port: 80
    targetPort: 80