---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../base/

# resources:
  # - ./01-sealed-secret.yaml

nameSuffix: -dev

namespace: development

patchesStrategicMerge:
  - ./nodeapp-deploy-patch.yaml