apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secretname
spec:
  encryptedData:
    username: AgCp8jeuDJyb/ThjXb/xrs5n3ixbeSNmUqNtNiaLwHs9eISIeY1SBBjO0Ogcz0rq/2bdJT1NMp7W4mD5/w0ExEp3IliBCTWhuAOeMVPlgXncW4wALZnRoP+LjYCLSUWQwvHQ1GnSLySig5EiVKZryOOFYmEzbDD3MLX7+nbsp4xr6AfqKZtJIFXL1j8mgWn3SX4gRW0LgaV/XkLJpH02oVo7e9PxKtGsU1kAbRPXMIdglcxy/u+cjRYMG1EUuCIsDFWhl2Ilz9Tnz0/Rq7GX5gZkFD0xmV1CdoVPq25rYme4LEy0Pt6ABqUh11Tq8rJiDoliBdsTPols4DvRhJTP1AylIXFynYxk+JeYomsj9mwv77fcgtx8fbgCu4GevPoBiqCeiD3m6FR+LsUDpQdNYpWUp9itKMDo18govt8gqQeG3oruV9+bEL9jxRzaW8oQluwW+ZVZDCV2TmfXzuMLDyCVnsF2XqUInjRd8SNKyom43ow/wNkqCYFqWtVvhi90pPjgztcE5Bqc4N5DjqATgIihgLTDPePO+6pnsoVEuMPJbuqezMLcZ/939YlA3JDSO8zHj7yLPut+JWFC4/MICwOr7hF8ETIeqB/5i8iXLBChf/KVXdJkD2EPZ5kxcIuH0ZjV9EH8rUubvUr9u0dx7CD90qyQ8XdVei5P4bKEYW5bpWaTb91HPVYIX/yUt/7BeKBKzPqvMosXkcTC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secretname
    type: Opaque

