apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  annotations: 
    argocd-image-updater.argoproj.io/image-list: ng=docker.io/reboot646/nginx:~1.0.0
    argocd-image-updater.argoproj.io/ng.update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-image-updater/nginx/chart/nginx
    repoURL: 'git@github.com:sauravrana646/argocd.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
